# permissions for end users to view profileinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profileinstance-viewer-role
rules:
- apiGroups:
  - weave.works
  resources:
  - profileinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weave.works
  resources:
  - profileinstances/status
  verbs:
  - get
