# permissions for end users to edit profileinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profileinstance-editor-role
rules:
- apiGroups:
  - weave.works
  resources:
  - profileinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weave.works
  resources:
  - profileinstances/status
  verbs:
  - get
